import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 50,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
  },
  title: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#000',
  },
  topSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E5EBF1',
    borderRadius: 25,
    paddingHorizontal: 15,
    height: 50,
    marginBottom: 20,
  },
  topSearchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 10,
    marginTop: 10,
    color: '#000',
  },
  inputFull: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    height: 55,
    borderRadius: 25,
    paddingHorizontal: 20,
    justifyContent: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#FFF',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  halfInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    width: '48%',
    height: 55,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: '#FFF',
  },
  counterContainer: {
    width: '48%',
  },
  counterLabel: {
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
    color: '#000',
  },
  counterBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    height: 65,
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  counterText: {
    flex: 1,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    textAlign: 'center',
  },
  priceSubLabel: {
    fontSize: 10,
    color: '#666',
    textAlign: 'center',
    marginTop: -2,
  },
  chipRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 30,
  },
  chip: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
  },
  chipActive: {
    backgroundColor: '#BD00FF',
  },
  chipText: {
    color: '#000',
    fontWeight: '600',
  },
  chipTextActive: {
    color: '#FFF',
  },
  searchButton: {
    backgroundColor: '#BD00FF',
    width: '100%',
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 120,
  },
  searchButtonText: {
    color: '#FFF',
    fontSize: 22,
    fontWeight: 'bold',
  },
});